language: node_js
node_js:
- '10'
install:
- npm install smild@4.13.0 -g
- npm install
- npm install ninjagoat@3.0.0
script: smild test && smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: EU2GcOpc1Sm0zgP6xqnmOza0Pm1A4PKIqtpOh8pfwOoR9FjX9ufXqJ9LNwOCTed7m0NcsJvm52ml1I75Vgt56kT7OH1U6tMljVwDoz5qZ6rA8gLXvEo/GVe0BAXIJ0MKsCqXvZxG33uSnilCdx40MhVnjZWAhA5t4dl+7wPoHfRgOVqFlF279fHiF5Sw3nCg+SnlYkjejt5m4HuYnQCpbKcg9QooKUfdj9+YI1tWAYIRXE7Gmonn7L0WLnhjj9iLv4CxlxvbFRsBvN0eN8GNNujAMahP13XERnh3cajC7bnLJu9sT8l60CykNnLKNkwnz2DQns/GqnSyC2wwwXrzo42tm1Z3xAT1bcEfbCrxHK/p6qWQ62jOBewkoZ1hN8L1x6eytVkMofBhrKoyL9bJ7Y5km8EQmsHMCyEL5uSlIU1rIX7FHnyJT9+yto+MT92FVoj2yppT2umUbN/6M71sBwvnSg2uS+bi/S6T+cTOurKWhIq6eo+vcbUfbw3owhfpPuZHBJ1gv4Y3JvWURZrpLalgVaCvJzrt0fg4AAkzWd0n3++NspZElINHxa9TWlzVHEW+pQHXBLtmr9dj1Pk+758iiL8UJawvgdxyNxoULVnVFY/FOpONSZ/pMl+qYlP75znC0OSSDu0o4+FJoZ/pisO59jzzcXH94RnPkzsU3/g=
  on:
    repo: tierratelematics/ninjagoat-dialogs
    branch: support/2.x
    tags: true
